services:
  postgres:
    image: postgres:18.1
    restart: always
    shm_size: 128mb
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    image: node:24
    restart: always
    user: node
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: bash -c "npm install && npx prisma generate && npm run start:dev"
    depends_on:
      - postgres

  frontend:
    image: node:24
    restart: always
    user: node
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: bash -c "npm install && npm run dev"
    depends_on:
      - backend

volumes:
  postgres_data:
