name: CI/CD Books Manager APP with Next.js and NestJS on AWS EC2

on:
  push:
    branches:
      - main

jobs:
  test_backend:
    name: Run tests on backend
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Configure Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Generate prisma
        run: npx prisma generate
        working-directory: backend

      - name: Format generated prisma
        run: sh format_generated_prisma_for_tests.sh
        working-directory: backend

      - name: Run tests
        run: npm test
        working-directory: backend

  test_frontend:
    name: Run tests on frontend
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Configure Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run tests
        run: npm test
        working-directory: frontend

  deploy:
    name: Deploy on EC2
    needs:
      - test_backend
      - test_frontend

    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Configure and send to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/book-manager-desafio-full-stack
            git pull origin main
            docker compose down
            docker compose --file docker-compose-production.yaml up -d